name: "QAS Deployment"

on:
    push:
        branches:
            - qas

jobs:
    deploy:
        uses: ./.github/workflows/deploy_base.yaml
        with:
            working-directory: .
            environment: "qas"
            aws-region: "ap-southeast-2"
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            MANAGEMENT_API_KEY: ${{ secrets.MANAGEMENT_API_KEY }}
